sudo: false
dist: xenial
language: csharp
mono: none
dotnet: 2.0.0
solution: Com.DanLiris.Service.Auth.sln
services:
    - docker
env:
    - ASPNETCORE_ENVIRONMENT=Test

before_install:
    
install: true

before_script:
    - sudo apt-get install libgdiplus
    - sleep 60

script:
    - dotnet restore Com.Danliris.Service.Auth.Test/Com.Danliris.Service.Auth.Test.csproj
    - dotnet build Com.Danliris.Service.Auth.Test/Com.Danliris.Service.Auth.Test.csproj
    - dotnet test Com.Danliris.Service.Auth.Test/Com.Danliris.Service.Auth.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

after_success:
    - curl -s https://codecov.io/bash > codecov
    - chmod +x codecov
    - ./codecov -f "/home/travis/build/danliris/com-danliris-service-auth/Com.Danliris.Service.Auth.Test/coverage.info"
